# Generated by Django 4.1.7 on 2023-03-07 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="startdate",
            new_name="start_date",
        ),
    ]
